import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/Header'
import clsx from 'clsx'
import FooterSection from '@/components/FooterSection'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Rent Car',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={clsx(inter.className, 'bg-slate-100/60')}>
        <Header />
        <main className='px-4'>{children}</main>
        <FooterSection />
      </body>
    </html>
  )
}
